pipeline:
  build_docker_image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t quay.io/ukhomeofficedigital/chisel:$${DRONE_COMMIT_SHA} .
    when:
      event:
        - push
        - tag

  scan:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    dockerfile: Dockerfile
    image_name: quay.io/ukhomeofficedigital/chisel:${DRONE_COMMIT_SHA}
    tolarates: medium
    fail_on_detection: true
    when:
      event: [push, tag]

  image_to_quay:
    image: docker:17.09.1
    secrets: [docker_password]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+chisel" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag quay.io/ukhomeofficedigital/chisel:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/chisel:latest
      - docker push quay.io/ukhomeofficedigital/chisel:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/chisel:latest
    when:
      event: push
      branch: master

  tagged_image_to_quay:
    image: docker:17.09.1
    secrets: [docker_password]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+chisel" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag quay.io/ukhomeofficedigital/chisel:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/chisel:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/chisel:$${DRONE_TAG}
    when:
      event: tag
