---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: extract_chisel_version
  pull: if-not-exists
  image: alpine:3.20.3
  commands:
  - grep -E "^ENV[[:space:]]+CHISEL_VERSION" Dockerfile
  - export CHISEL_VERSION=$(grep -E "^ENV[[:space:]]+CHISEL_VERSION" Dockerfile | awk -F '=' '{print $2}' | tr -d ' ')
  - echo "CHISEL_VERSION=${CHISEL_VERSION}" > .chisel_version
  - cat .chisel_version

- name: build_docker_image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    # wait for docker service to be up before running docker build
  - /usr/local/bin/wait
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - export CHISEL_VERSION=$(cat .chisel_version | cut -d '=' -f2)
  - docker build -t quay.io/ukhomeofficedigital/chisel:$${DRONE_COMMIT_SHA} .
  when:
    event:
    - push
    - tag

- name: scan_image_with_trivy
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  environment:
    IMAGE_NAME: quay.io/ukhomeofficedigital/chisel:${DRONE_COMMIT_SHA}
    TRIVY_SKIP_FILES: /etc/keys/key
  commands:
    - trivy image quay.io/ukhomeofficedigital/chisel:${DRONE_COMMIT_SHA} --exit-code 1
  when:
    event:
    - push
    - tag

- name: push_image_with_branch_tag
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - export CHISEL_VERSION=$(cat .chisel_version | cut -d '=' -f2)
  - docker login -u="ukhomeofficedigital+chisel" -p=$${DOCKER_PASSWORD} quay.io
  - docker tag quay.io/ukhomeofficedigital/chisel:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/chisel:$${CHISEL_VERSION}-${DRONE_BRANCH}
  - docker push quay.io/ukhomeofficedigital/chisel:$${CHISEL_VERSION}-${DRONE_BRANCH}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
    branch:
      exclude:
      - master

- name: image_to_quay_master
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - export CHISEL_VERSION=$(cat .chisel_version | cut -d '=' -f2)
  - docker login -u="ukhomeofficedigital+chisel" -p=$${DOCKER_PASSWORD} quay.io
  - docker tag quay.io/ukhomeofficedigital/chisel:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/chisel:latest
  - docker push quay.io/ukhomeofficedigital/chisel:$${DRONE_COMMIT_SHA}
  - docker push quay.io/ukhomeofficedigital/chisel:latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

- name: tagged_image_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - export CHISEL_VERSION=$(cat .chisel_version | cut -d '=' -f2)
  - docker login -u="ukhomeofficedigital+chisel" -p=$${DOCKER_PASSWORD} quay.io
  - docker tag quay.io/ukhomeofficedigital/chisel:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/chisel:$${DRONE_TAG}
  - docker push quay.io/ukhomeofficedigital/chisel:$${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind